### ISSUE TITLE
External entity missing in a level

### ISSUE THREAD

**Issue by arghyakusumdas** [martinezi655/cs3530Project#2]
Admin is missing in level-0 diagram

**Comment by CMelhaire** [comment]
External entity (Admin) is missing in level-0 of the DFD.

**Comment by CMelhaire** [comment]
Added the missing entity and its data flow arrows, let me know if I missed anything, otherwise I'll go ahead and close it out.  (New files are Assignment2_DFD_version2.vsdx/pdf)

**Comment by murphypatr** [comment]
Admin was added, looks fine.

**Comment by martinezi655** [comment]
Needed to find some additional information for this

**Comment by Angel0117** [comment]
The diagrams look good to me, I don't see anything missing from them now.

**Comment by commarch** [comment]
Admin has been added, looks like this issue has been resolved
