### ISSUE TITLE
Many boxes with same name leads to unbalanced arrows

### ISSUE THREAD

**Issue by arghyakusumdas** [martinezi655/cs3530Project#3]
You can use one box per external entity and then balance the number of arrow in all the levels

**Comment by martinezi655** [comment]
This was a bit difficult because the information on the DFD was different from what we have learned in previous classes and the information online wasn't extremely helpful.

**Comment by martinezi655** [comment]
We were able to piece it together piece by piece and come up with a better version of the DFD

**Comment by commarch** [comment]
There are no longer duplicate external entities, and all arrows are balanced between level 1 and level 0

**Comment by murphypatr** [comment]
The arrows do look balanced, looks good.

**Comment by CMelhaire** [comment]
Looks much better now - everything seems pretty balanced.

**Comment by Angel0117** [comment]
Looks like everything is balanced now for all the level diagrams.

**Comment by commarch** [comment]
Looks good to me. Arrows seem balanced
