### ISSUE TITLE
External Entities and Data Dictionary Problem

### ISSUE THREAD

**Issue by arghyakusumdas** [martinezi655/cs3530Project#4]
External entites in level1 became data dictionary in level 2. This is wrong. Please change that.

**Comment by martinezi655** [comment]
These were completed when we revised the visio document

**Comment by murphypatr** [comment]
These look like they've been changed correctly.

**Comment by CMelhaire** [comment]
Everything looks like it's okay to me as well.

**Comment by Angel0117** [comment]
Looks good to me, I don't see any problems with it.

**Comment by commarch** [comment]
Looks like everything was figured out. Good with me
