### ISSUE TITLE
Adhere to the symbol

### ISSUE THREAD

**Issue by arghyakusumdas** [martinezi655/cs3530Project#5]
Please use the conventional symbols for DFD. Do not mix with external entities and data dictionary

**Comment by CMelhaire** [comment]
Some symbols in the DFD have been mixed up; needs modification so that all levels adhere to the Gane-Sarson notation.

**Comment by CMelhaire** [comment]
Looks like everything should be good now; all processes, data-flows, and external entities now match their default G-S notations provided by Visio.  (New files are Assignment2_DFD_version2.vsdx/pdf)

**Comment by murphypatr** [comment]
Looks like the shapes/symbols are correct to me.

**Comment by martinezi655** [comment]
There are two standards for the symbols, we used what was most available in our memories and what we learned in analysis and design.

**Comment by Angel0117** [comment]
Everything here looks fine to me from what I can remember about this stuff.

**Comment by commarch** [comment]
Symbols look like they have been fixed.
