### ISSUE TITLE
Problem in GitHub Management

### ISSUE THREAD

**Issue by murphypatr** [martinezi655/cs3530Project#6]
Every group member should post a message for all issues.

**Comment by murphypatr** [comment]
We understood the process

**Comment by martinezi655** [comment]
We understood the process

**Comment by CMelhaire** [comment]
We understood the process

**Comment by commarch** [comment]
We understood the process

**Comment by Angel0117** [comment]
Understood

**Comment by murphypatr** [comment]
Everyone's understood, so we're closing the issue.
