### ISSUE TITLE
Do NOT use 'database' as an entity

### ISSUE THREAD

**Issue by arghyakusumdas** [martinezi655/cs3530Project#8]
It is ER diagram (Not DFD). So the entire thing is a database. everything is a table/collections.
But otherwise the database looks good.
Figure out how can you reconfigure it without both the 'Database' blocks in your diagram so that all the operations can be done with minimum redundancy. Submit a new one to get back 5 points

**Comment by murphypatr** [comment]
Uploaded a revised ERD (titled Assignment4_ERD_rev1). Let me know if you guys think there's anything else we need to change to it.

**Comment by murphypatr** [comment]
One last-minute revision using group input. current version is Assignment4_ERD_rev2.
